### ISSUE TITLE
error on 'Close all terminals' with 10 terminals for one file

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#13]
called 'close all terminals' from Plugins menu.

```
Python 3.8
Init: cuda_console_complete
Init: cuda_terminal_plus
Loaded session: "history session.json", 20ms, 1 file(s)
Init: cuda_hilite_occurrences
Startup: 220ms, plugins: 40ms (console_complete 19ms, terminal_plus 21ms, hilite_occurrences 5ms)
 [activating panel: <('Terminal+', True)>]
Init: cudatext
Init: cuda_addonman
 [activating panel: <Terminal+>]
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_terminal_plus/__init__.py", line 1785, in cmd_close_cur_term
    self.termbar.run_cmd(CMD_CLOSE_CURRENT)
NameError: name 'CMD_CLOSE_CURRENT' is not defined
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_terminal_plus/__init__.py", line 1785, in cmd_close_cur_term
    self.termbar.run_cmd(CMD_CLOSE_CURRENT)
NameError: name 'CMD_CLOSE_CURRENT' is not defined
 [activating panel: <Terminal+>]
 [activating panel: <Terminal+>]
 [activating panel: <Terminal+>]
 [activating panel: <Terminal+>]
 [activating panel: <Terminal+>]
 [activating panel: <Terminal+2>]
 [activating panel: <Terminal+3>]
 [activating panel: <Terminal+>]
 [activating panel: <Terminal+>]
```

**Comment by halfbrained** [comment]
problem was with the command 'Close terminal' instead, fixed
