### ISSUE TITLE
ping, then error

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#29]
entered 'ping ya.ru'. after 4 sec pressed Break on keyboad of PC.
```
Python 3.8
Init: cuda_console_complete
Init: cuda_terminal_plus
Loaded session: "history session.json", 20ms, 0 file(s)
Startup: 210ms, plugins: 40ms (console_complete 20ms, terminal_plus 22ms)
 [activating panel: <('Terminal+', True)>]
Init: cudatext
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/user/.config/cudatext/py/cuda_terminal_plus/__init__.py", line 152, in run
    self.run()
  File "/home/user/.config/cudatext/py/cuda_terminal_plus/__init__.py", line 152, in run
    s = self.Cmd.ch_out.read(READSIZE)
ValueError: I/O operation on closed file
    s = self.Cmd.ch_out.read(READSIZE)
ValueError: I/O operation on closed file
```

**Comment by halfbrained** [comment]
fixed (f10ee5442f76b707aa65a447f937d37c83a09d6c)
